<a href="https://colab.research.google.com/github/fawazdhianabil/Basic-Python-Programming-for-Data-Science/blob/main/TugasBagian6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#1. Membuat Numpy Array
##Numpy Array dengan List
arraynabil = np.array([100,90,80,80,90,100])
print('Nilai Nabil :', arraynabil)

Nilai Nabil : [100  90  80  80  90 100]


In [ ]:
#2. Vektor dengan Numpy Array
n = int(input('Masukkan Jumlah Kolom = '))
nabil = np.random.randint(1,10, size = (1,n))
print(nabil)

Masukkan Jumlah Kolom = 5
[[8 7 3 3 1]]


In [ ]:
#3. Operasi Vektor
print(nabil+2)
print(nabil-2)
print(nabil*2)

[[9 8 4 4 2]]
[[7 6 2 2 0]]
[[8 7 3 3 1]]


In [ ]:
#4. Matriks dengan Numpy Array
matriksnbl = np.array([[1, 2],[4,5]])
print(matriksnbl)

[[1 2]
 [4 5]]


In [ ]:
#5. Operasi Matriks 
print("-"*6)
print('Penjumlahan Skalar')
print(matriksnbl+2)
print("-"*6)
print('Pengurangan Skalar')
print(matriksnbl-2)
print("-"*6)
print('Perkalian Skalar')
print(matriksnbl*2)
print("-"*6)
print('Perkalian Matriks')
print(matriksnbl*(np.array([[3,2],[6,5]])))

------
Penjumlahan Skalar
[[3 4]
 [6 7]]
------
Pengurangan Skalar
[[-1  0]
 [ 2  3]]
------
Perkalian Skalar
[[ 2  4]
 [ 8 10]]
------
Perkalian Matriks
[[ 3  4]
 [24 25]]


In [ ]:
#6. Dot Product dan Cross Product
anabil = np.array([2,1])
bnabil = np.array([3,4])
print('Hasil Cross Product = ', np.cross(anabil,bnabil))
print('Hasil Dot Product =', np.dot(anabil,bnabil))

Hasil Cross Product =  5
Hasil Dot Product = 10


In [ ]:
#7. Aljabar Linier
matriksnbl
print('-'*6)
print('Inverse matriksnbl = ' , np.linalg.inv(matriksnbl))
print('-'*6)
print('Determinan matriksnbl =', np.linalg.det(matriksnbl))
print('-'*6)
print('Mengambil elemen diagonal matriksnbl = ', matriksnbl.diagonal())


------
Inverse matriksnbl =  [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
------
Determinan matriksnbl = -2.9999999999999996
------
Mengambil elemen diagonal matriksnbl =  [1 5]


In [ ]:
#PCA dengan Numpy
#Maaf mas saya belum mengerti algoritma nya


PCA adalah suatu metode untuk I biasa digunakan untuk mereduksi dimensi linier. Ide di balik PCA adalah untuk menemukan representasi data berdimensi lebih rendah yang menyimpan informasi sebanyak mungkin.